True = TRUE
repair_json("True", return_objects=True)
repair_json("False", return_objects=True)
repair_json("Null", return_objects=True)
repair_json("1", return_objects=True)
repair_json("[]", return_objects=True)
repair_json("[1, 2, 3, 4]", return_objects=True)
repair_json("{}", return_objects=True)
repair_json('{ "key": "value", "key2": 1, "key3": True }', return_objects=True)
repair_json("true", return_objects=True)
repair_json("false", return_objects=True)
repair_json("null", return_objects=True)
repair_json("1.2", return_objects=True)
repair_json("[", return_objects=True)
repair_json("[1, 2, 3, 4", return_objects=True)
repair_json("{", return_objects=True)
repair_json('{ "key": value, "key2": 1 "key3": null }', return_objects=True)
repair_json('{"name": "John", "age": 30, "city": "New York"}')
repair_json('{"employees":["John", "Anna", "Peter"]} ')
repair_json('{"key": "value:value"}')
repair_json('{"text": "The quick brown fox,"}')
repair_json('{"text": "The quick brown fox won\'t jump"}')
repair_json('{"key": ""')
repair_json('{"key1": {"key2": [1, 2, 3]}}')
repair_json('{"key": 12345678901234567890}')
repair_json('{"key": "value\u263a"}')
repair_json('{"key": "value\\nvalue"}')
repair_json("[{]")
repair_json("   {  }   ")
repair_json("[")
repair_json("]")
repair_json("{")
repair_json("}")
repair_json('{"')
repair_json('["')
repair_json("{foo: [}")
repair_json('"')
repair_json("\n")
repair_json(" ")
repair_json("[[1\n\n]")
repair_json("string")
repair_json("stringbeforeobject {}")
repair_json('  {"key": true, "key2": false, "key3": null}')
repair_json('{"key": TRUE, "key2": FALSE, "key3": Null}   ')
repair_json("{'key': 'string', 'key2': false, \"key3\": null, \"key4\": unquoted}")
repair_json('{"name": "John", "age": 30, "city": "New York')
repair_json('{"name": "John", "age": 30, city: "New York"}')
repair_json('{"name": "John", "age": 30, "city": New York}')
repair_json('{"name": John, "age": 30, "city": "New York"}')
repair_json('{“slanted_delimiter”: "value"}')
repair_json('{"name": "John", "age": 30, "city": "New')
repair_json('{"name": "John", "age": 30, "city": "New York, "gender": "male"}')
repair_json('[{"key": "value", COMMENT "notes": "lorem "ipsum", sic." }]')
repair_json('{"key": ""value"}')
repair_json('{"key": "value", 5: "value"}')
repair_json('{"foo": "\\"bar\\""')
repair_json('{"" key":"val"')
repair_json('{"key": value "key2" : "value2" ')
repair_json('{"key": "lorem ipsum ... "sic " tamet. ...}')
repair_json('{"key": value , }')
repair_json('{"comment": "lorem, "ipsum" sic "tamet". To improve"}')
repair_json('{"key": "v"alu"e"} key:')
repair_json("[1, 2, 3,")
#####ERROR
repair_json("[1, 2, 3, ...]")
####ERROR
repair_json("[1, 2, ... , 3]")
repair_json("[1, 2, '...', 3]")
####ERROR
repair_json("[true, false, null, ...]")
repair_json('["a" "b" "c" 1')
repair_json('{"employees":["John", "Anna",')
repair_json('{"employees":["John", "Anna", "Peter')
repair_json('{"key1": {"key2": [1, 2, 3')
repair_json('{"key": ["value]}')
repair_json('["lorem "ipsum" sic"]')
repair_json('{"key1": ["value1", "value2"}, "key2": ["value3", "value4"]}')
repair_json('[ "value", /* comment */ "value2" ]')
repair_json('{"key": ["value" "value1" "value2"]}')
repair_json('{"key": ["lorem "ipsum" dolor "sit" amet, "consectetur" ", "lorem "ipsum" dolor", "lorem"]}')
repair_json('{"k"e"y": "value"}')
repair_json('["key":"value"}]')
repair_json("'\"'")
repair_json('{"key": \'string"\n\t\\le\'')
repair_json(
  "{\"real_content\": \"Some string: Some other string \\t Some string <a href=\\\"https://domain.com\\\">Some link</a>\"}"
)

repair_json('{"key_1\n": "value"}')
repair_json('{"key\t_": "value"}')
repair_json("{\"key\": '\u0076\u0061\u006c\u0075\u0065'}")
repair_json('{"key": "\\u0076\\u0061\\u006C\\u0075\\u0065"}', skip_json_loads=True)
repair_json("{       ")
repair_json('{"": "value"')
repair_json('{"value_1": true, COMMENT "value_2": "data"}')
repair_json('{"value_1": true, SHOULD_NOT_EXIST "value_2": "data" AAAA }')
repair_json('{"" : true, "key2": "value2"}')
repair_json('{"answer":[{"traits":"Female aged 60+","answer1":"5"}]}')
repair_json('{ "words": abcdef", "numbers": 12345", "words2": ghijkl" }')
repair_json('{"number": 1, "reason": "According...", "ans": "YES"}')
repair_json('{ "a" : "{ b": {} }" }')
repair_json('{"b": "xxxxx" true}')
repair_json('{"key": "Lorem "ipsum" s,"}')
repair_json('{"lorem": ipsum, sic, datum.",}')
repair_json('{"lorem": sic tamet. "ipsum": sic tamet, quick brown fox. "sic": ipsum}')
repair_json('{"lorem_ipsum": "sic tamet, quick brown fox. }')
