# wrappers.R

# Ensure jsonrepair.R is sourced if not already (for standalone testing)
# In a real package, this would be handled by NAMESPACE
# source("jsonrepair.R") # Uncomment for local testing if needed

#' @title Repair and Parse JSON Text
#' @description Repairs a malformed JSON string generated by LLMs and parses it into an R object.
#' @param text A character string containing the malformed JSON.
#' @param logging Logical, whether to enable internal logging of repair steps. Defaults to FALSE.
#' @param stream_stable Logical, whether to enable stable parsing for streaming JSON. Defaults to FALSE.
#' @return An R object (list, vector, string, numeric, logical, or NULL) representing the repaired JSON.
#'   If logging is TRUE, returns a list containing `json` (the parsed object) and `log` (a list of log messages).
#' @examples
#' \dontrun{
#'   # Example with a simple malformed JSON string
#'   malformed_json_str <- '{ "name": "Alice", "age": 30, "city": "New York", }'
#'   repaired_json <- repair_json_text(malformed_json_str)
#'   print(repaired_json)
#'
#'   # Example with missing quotes and comments
#'   malformed_json_str2 <- '{"item": apple, // a fruit
#'     "quantity": 10 /* number of items */
#'   }'
#'   repaired_json2 <- repair_json_text(malformed_json_str2)
#'   print(repaired_json2)
#'
#'   # Example with logging enabled
#'   repaired_with_log <- repair_json_text(malformed_json_str, logging = TRUE)
#'   print(repaired_with_log$json)
#'   print(repaired_with_log$log)
#' }
#' @export
repair_json_text <- function(text, logging = FALSE, stream_stable = FALSE) {
  parser <- JSONParser$new(json_str = text, logging = logging, stream_stable = stream_stable)
  parser$parse()
}

#' @title Repair and Parse JSON from a File
#' @description Reads a JSON file, repairs malformed content generated by LLMs, and parses it into an R object.
#' @param file_path A character string specifying the path to the JSON file.
#' @param logging Logical, whether to enable internal logging of repair steps. Defaults to FALSE.
#' @param stream_stable Logical, whether to enable stable parsing for streaming JSON. Defaults to FALSE.
#' @return An R object (list, vector, string, numeric, logical, or NULL) representing the repaired JSON.
#'   If logging is TRUE, returns a list containing `json` (the parsed object) and `log` (a list of log messages).
#' @examples
#' \dontrun{
#'   # Create a dummy malformed JSON file for demonstration
#'   temp_file <- tempfile(fileext = ".json")
#'   writeLines('{ "product": "Laptop", "price": 1200, "currency": "USD", }', temp_file)
#'   repaired_file_json <- repair_json_file(temp_file)
#'   print(repaired_file_json)
#'   unlink(temp_file) # Clean up the temporary file
#' }
#' @export
repair_json_file <- function(file_path, logging = FALSE, stream_stable = FALSE) {
  if (!file.exists(file_path)) {
    stop("File not found: ", file_path)
  }
  text <- readChar(file_path, file.info(file_path)$size)
  parser <- JSONParser$new(json_str = text, logging = logging, stream_stable = stream_stable)
  parser$parse()
}
